### ISSUE TITLE
CAD file request

### ISSUE THREAD

**Issue by fcaponetto** [Adrien-Legrand/AS5X47#2]
First of all, thanks a lot for your contribution.

Is it possible to have the CAD file to print it out?

**Comment by Adrien-Legrand** [comment]
Hi, 
Which CAD file are you talking about ? This repository is a software for an Arduino library.

**Comment by fcaponetto** [comment]
The CAD file that I was referring to is the one used to test the encoder:
![image](https://user-images.githubusercontent.com/11439681/107847055-56206e80-6de0-11eb-9a16-b4128a44bdbd.png)

**Comment by Adrien-Legrand** [comment]
Hi, 
Sorry, I had a student licence for the CAD Software when I designed these parts, that doesn't allow me to share the files.
