### ISSUE TITLE
OTP programming - ABIRES and Zero Position

### ISSUE THREAD

**Issue by MatejsLab** [Adrien-Legrand/AS5X47#5]
Hi Adrien,
I got a request at a project job to write code for sensor AS5047P, the code, for now, runs on Arduino Uno. 
They wish to configure the sensor and make it permanent, I ask for your help to make it work.
They need to write ABIRES and Zero Position to the sensor and program the OTP, so the sensor remembers the settings.

I used your library to configure sensor settings which worked fine, but I was unable to program OTP register.
I also tried to pass raw commands to the sensor, it looked like it worked, but it seems like the sensor didn't remember its settings after the power cycle.
I followed this datasheet for programming OTP https://ams.com/documents/20143/36005/AS5047P_DS000324_3-00.pdf 
It looks like I got something wrong, but I can't figure out what the bug is.

It would be awesome if you would be able to test this code and maybe find out the bug by next week's Thursday 2.2.23. 
If possible you can tweak my code to make it work.

It would be great if your library could support OTP programming natively but it seems like the commands for the PROG register refused to pass into the sensor.

Here is the code I wrote, it has a serial interface for some configuration.

[ConfigureSensor_AS5074_MK_V1.10.zip](https://github.com/Adrien-Legrand/AS5X47/files/10521753/ConfigureSensor_AS5074_MK_V1.10.zip)

Thanks a lot, in advance.

**Comment by pk77412378** [comment]
Hello Adrien,

I want to configure the AS5147 IC as ABI+PWM for that i used the code written by you.
After flashing the software, we get accurate pulses but when we remove the communication pins(SS, CLK, MISO,MOSI) we did not get pulses.

so i want to flash the software in non volatile memory.
Can you help me regarding this.

With warm regards
Pawan Kumar

**Comment by Adrien-Legrand** [comment]
Hello @MatejsLab and @pk77412378,

@MatejsLab, I read your code very quickly, which seems correct according to AMS specifications.

I wrote a basic example using OTP in the develop branch, I just tested it successfully with an AS5047D.
Please let me know if this example helped you in order to make a new release of the library including it.

[https://github.com/Adrien-Legrand/AS5X47/blob/6ef28b3829a2f025609a71fbfc10a3b7aaad0b20/examples/ConfigureSensorOTP/ConfigureSensorOTP.ino](https://github.com/Adrien-Legrand/AS5X47/blob/6ef28b3829a2f025609a71fbfc10a3b7aaad0b20/examples/ConfigureSensorOTP/ConfigureSensorOTP.ino)

Adrien

**Comment by MatejsLab** [comment]
Sounds great, but the link doesn't work, it brings up an empty GitHub page.

I also managed to configure OTP back in February, I added HEX commands in the code directly.

Looks like other users will still require your code, just repost the right link.

Thanks for developing a library.

**Comment by JustSomeRandomDIYGuy** [comment]
@pk77412378
there are some notes below the Pin-Assignment table in the data sheet that states:

> Note(s):
> 1. Floating state of a digital input is not allowed.
> 2. If SPI is not used, a Pull up resistor on CSn is required.
> 3. If SPI is not used, a Pull down resistor on CLK and MOSI is required.
> 4. If SPI is not used, the pin MISO can be left open.
> 5. If ABI, UVW or PWM is not used, the pins can be left open

Maybe that is the reason for your issue?

**Comment by MatejsLab** [comment]
The issue is now closed, as  may project is working fine. The library was updated by @Adrien-Legrand  to include OTP functionality.

Indeed @JustSomeRandomDIYGuy the ISP resistors are mandatory to prevent unpredictable bahaviour.

@pk77412378 if the issue persist, weacome to reopen issue, otherwise OTP is now suported so i guess my issue is being closed.

I have no more hardware to test, but the library OTP commands look correct.

Thanks for an upgrade, i am sure that many users will appriciate new functionality.
